### ISSUE TITLE
<header class="header">

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#21]
для чого прописувати клас тут ?

**Comment by Oleksandr07** [comment]
На IE тег header погано підтримується

**Comment by sera2007** [comment]
на скільки не підтримується ?

**Comment by mekela** [comment]
Тому що бувають такі випадки коли тег header використовується як заголовок статті, а не шапка сайту.

**Comment by mekela** [comment]
а там все чітко прописано
