### ISSUE TITLE
minify

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#22]
чому б не мініміфікувати фінальний файл ?
http://c2n.me/3vohFeN

**Comment by mekela** [comment]
compact підтримує коментарі які додані в sass, а minify їх видаляє.

**Comment by sera2007** [comment]
а нашо нам коментарі в фінальному файлі ?

**Comment by mekela** [comment]
Наприклад, для полегшення життя верстальнику не з нашої студії (який не використовує sass), або для швидкої навігації по документу, ну і залишання коментарів це признак хорошого тону у верстці.

**Comment by sera2007** [comment]
в такому разі буде достатнім папку із cscc залишати в проекті. Або фінально мати два файли, зжатий і не зжатий
