### ISSUE TITLE
Перший екран - стилі

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#23]
Як ти відносишся до ідеї створення окремого файлук стилів для першого еркану проекту ? Це покращить завантаждення проекту на мобільних прострояїх. Стилі першого еркану будуть заванажуватися в хедері, а всі інші десь перед закритим тегом body

**Comment by mekela** [comment]
тобто створювати і підключати ще один файл стилів?

**Comment by sera2007** [comment]
ага, для підвищення швидкості

**Comment by mekela** [comment]
я думаю, якщо збільшити кількість звертань до серверу, то приросту швидкості не буде.
