### ISSUE TITLE
'-' замість '_'

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#24]
contacts_wrapper -> contacts-wrapper
Як на мене це трішки економить час

**Comment by Oleksandr07** [comment]
В якому плані економить?

**Comment by sera2007** [comment]
не потрібно додатково нажиаті shift кожен раз, можна провести експеремент)
За скільки часу вадсться надрукувати 10 рисок і 10 нижніх підкреслювань)
але потрібно кожен раз натискати окремо шифт а не тримати нажатим.

Потім подивитися скільки нижніх підкреслювать є в проекті і порахувати кількість зекономленого часу)

**Comment by mekela** [comment]
я так пишу тому що зручніше копіювати назви класів в стилі.

**Comment by sera2007** [comment]
а чого саме так зручніше, розпиши детальніше ?

**Comment by mekela** [comment]
спробуй швидко скопіювати (два рази клікнувши мишою по слову): 
contacts-page 
або
contacts_page
