### ISSUE TITLE
Швидкість завантаження

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#25]
Чого б не закинути всі скрипти і стилі, крім screen.css в низ сторінки ?
Це дасть приріст у швидкості
- додати async для скриптів

**Comment by mekela** [comment]
тому що так правильніше по логіці і по семантиці

**Comment by sera2007** [comment]
по логіці - в чому саме правильніше ? по чиїй логіці ?

семантика не так важлива як швидкість. Сайтами користуються користувачі, яким пофігу на семантику, але коли сайт вантажиться довше ніж зазвичай, вони його просто вирубають і йдуть далі)

**Comment by mekela** [comment]
думаю найкращим рішенням в швидкості, буде зєднання всіх стилей і дописування для script async

**Comment by mekela** [comment]
але тоді файл стилів буде нечитабельним

**Comment by sera2007** [comment]
я думаю це вирішиться використаням збдірників проектів, результуючий файл стилів тоді з зжатій не зжатій версіях, зжата буде підключатися.
