### ISSUE TITLE
_mobile.scss

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#27]
Додати більше прикладів для ipad, iphone різних орієнтацій

**Comment by sera2007** [comment]
- стандартні розширення туди вписати, хай будуть по замовчуванні. пропоную оірєнтуватися на розширення bootstrap

**Comment by mekela** [comment]
на ділі я користуюсь своїми значеннями і окремо міксін для айпада і айфона не використовую. Тому буде краще просто зменшити до одного міксіна.

**Comment by sera2007** [comment]
ок, згоден, тоді зменш, щоб не заважало

**Comment by sera2007** [comment]
але ж ти не змінив нічого ?)

**Comment by mekela** [comment]
https://github.com/mekela/template_sass/commit/bcabd08174a526e91d0bf771310addf59f4ee7c1
