### ISSUE TITLE
Вигляд структури файлів в описі

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#5]
Думаю є сенс зробити ось так, наприклад:

├── app/                       # Исходники
│   ├── blocks/                # Блоки
│   │   └── block/             # Блок
│   │       ├── block.jade     # Разметка блока
│   │       ├── block.js       # Скрипт блока
│   │       └── block.styl     # Стили блока
│   ├── data/                  # Данные в формате JSON
│   ├── pages/                 # Страницы
│   │   └── index.jade         # Разметка страницы
│   ├── icons/                 # SVG иконки для генерации векторного спрайта
│   ├── sprite/                # PNG иконки для генерации растрового спрайта
│   ├── resources/             # Статические файлы для копирования в dist
│   ├── scripts/               # Скрипты
│   │   ├── app.js             # Главный скрипт
│   │   └── debug.js           # Идентификация отладки на локальном сервере
│   └── styles/                # Стили

**Comment by mekela** [comment]
Думаю має бути більш звичний вигляд
