### ISSUE TITLE
Автоматизація задач

### ISSUE THREAD

**Issue by sera2007** [mekela/template_sass#7]
Думаю є сенс копнути трохи глибше і налаштувати автоматизацію (gulp) та збірку проекта, як на мене є важливим:
1) компіляція scss
2) мініміфікаці стилів і скриптів із збереженням оригіналів
3) оптимізація зображень
4) перевірка валідації
5) додавання автопрефіксів
6) перевірка стилів і скриптів нашим правилам написання правил jshint, csshint

**Comment by mekela** [comment]
Це вже іншому шаблоні, який буде називатися gulp(or grunt) template
